# Generated by Django 4.1 on 2022-08-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_nome', models.CharField(blank=True, max_length=200, verbose_name='Nome')),
                ('empresa_atividade', models.CharField(blank=True, max_length=200, verbose_name='Atividade')),
                ('empresa_cnpj', models.CharField(blank=True, max_length=200, verbose_name='CNPJ')),
                ('empresa_endereco', models.CharField(blank=True, max_length=200, verbose_name='Endereço')),
                ('empresa_telefone', models.CharField(blank=True, max_length=200, verbose_name='Telefone')),
                ('empresa_email', models.CharField(blank=True, max_length=200, verbose_name='E-mail')),
                ('empresa_servico', models.CharField(blank=True, max_length=200, verbose_name='Serviço')),
            ],
        ),
    ]
