# Generated by Django 4.1 on 2022-09-09 14:58

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CalendarioCreated', models.DateTimeField(auto_now_add=True, verbose_name='TimeStamp')),
            ],
            options={
                'verbose_name': 'Calendario',
                'verbose_name_plural': 'Calendarios',
                'ordering': (),
            },
        ),
        migrations.AddField(
            model_name='pessoas',
            name='pessoa_imagem',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name=app1.models.upload_image_formater),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='ativo',
            field=models.CharField(default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='ativo',
            field=models.CharField(default='S', max_length=1),
        ),
    ]
