# Generated by Django 4.1 on 2022-08-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_horarios_locais_pessoas_servicos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoas',
            name='pessoa_cpf',
        ),
    ]
