# Generated by Django 4.1 on 2022-08-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_pessoas_pessoa_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='pessoa_cpf',
            field=models.CharField(blank=True, max_length=100, verbose_name='CPF'),
        ),
    ]
