# Generated by Django 4.1 on 2022-09-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20220909_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='pessoa_senha',
            field=models.CharField(default='Senha', max_length=100, verbose_name='Senha da Pessoa'),
        ),
    ]
