# Generated by Django 4.1 on 2022-09-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agendai_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='cpf',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='nascimento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
