# Generated by Django 4.1 on 2022-10-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agendai_app', '0002_agendamento_cpf_agendamento_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='dia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
