# Generated by Django 4.1 on 2022-10-04 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendario',
            options={},
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='CalendarioCreated',
        ),
        migrations.AddField(
            model_name='calendario',
            name='course_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='calendario',
            name='course_teacher',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='calendario',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='calendario',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='calendario',
            name='helptype',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='calendario',
            name='timeblock',
            field=models.CharField(choices=[('A', '8:00-8:20'), ('B', '8:20-8:40'), ('C', '8:40-9:00'), ('D', '9:00-9:20'), ('E', '9:20-9:40'), ('F', '9:40-10:00')], default='A', max_length=10),
        ),
    ]
