# Generated by Django 4.1 on 2022-10-07 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0002_alter_calendario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='pessoa_usuario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
    ]
