# Generated by Django 4.1 on 2022-10-10 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_calendario_timeblock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendario',
            old_name='course_teacher',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='calendario',
            old_name='course_name',
            new_name='nome_completo',
        ),
        migrations.RenameField(
            model_name='calendario',
            old_name='helptype',
            new_name='serviço',
        ),
    ]
