# Generated by Django 4.1 on 2022-10-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_calendario_timeblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendario',
            name='timeblock',
            field=models.CharField(choices=[('A', '9:00-10:00'), ('B', '10:00-11:00'), ('C', '11:00-12:00'), ('D', '14:00-15:00'), ('E', '15:00-16:00'), ('F', '16:00-17:00'), ('G', '17:00-18:00'), ('H', '18:00-19:00'), ('I', '19:00-20:00'), ('J', '20:00-21:00')], default='A', max_length=10),
        ),
    ]
