# Generated by Django 4.1 on 2022-10-20 13:15

from django.db import migrations
from app1.models import Pessoas_Juridicas

Default_Empresas = {
    ('Jiu-Jitsu', '00.000.000/0001-00', 'Treinamento','Escola de Jiu-Jitsu Jaguarunense',
    '(48) 98855-7770', 'henrique_cruz@hotmail.com','Rua João José Vieira, s/n'),
    ('Estética','33.257.695/000-14', 'Beleza', 'Estética Beatriz Bittencourt',
    '(48) 99922-7103', 'estetica.beatrizb@gmail.com','Rua Santa Augusta, 426 - Braço do Norte')
}

def add_empresas(apps, schema_editor):
    Empresas = apps.get_model('app1','Pessoas_Juridicas')

    for Vatividade, Vcnpj, Vservico, Vnome, Vtelefone, Vemail, Vendereco in Default_Empresas:
        empresa = Pessoas_Juridicas(pj_atividade=Vatividade, pj_cnpj=Vcnpj, pj_servico=Vservico,
         pessoa_nome=Vnome, pessoa_telefone=Vtelefone, pessoa_email=Vemail, pessoa_endereco=Vendereco)
        empresa.save()
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_calendario_timeblock'),
    ]

    operations = [
        migrations.RunPython(add_empresas)
    ]
